AllCops:
  Exclude:
    - 'aut-api-rest/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 250

Style/GlobalVars:
  Enabled: false

Metrics/ModuleLength:
  Max: 150

Metrics/PerceivedComplexity:
  Max: 100

Metrics/AbcSize: 
  Max: 100

Metrics/MethodLength: 
  Max: 100

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 100

Metrics/ClassLength:
  Max: 150

Style/ClassVars:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false